services:
  nginx:
    image: nginx:alpine
    container_name: nginx-lb
    hostname: nginx-lb
    ports:
      - 9999:9999
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - backend
    depends_on:
      - server-01
      - server-02
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: '30MB'

  server-01:
    build: .
    container_name: server-01
    hostname: server-01
    ports:
      - 8081:8080
    expose:
      - '8080'
    networks:
      - backend
      - payment-processor
    command: ["server"]
    environment:
      - LISTEN_ADDR=:8080
      - REDIS_URL=redis:6379
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
    depends_on:
      - redis
    deploy:
      resources:
        limits:
          cpus: '0.65'
          memory: '80MB'

  server-02:
    build: .
    container_name: server-02
    hostname: server-02
    command: ["server"]
    ports:
      - 8082:8080
    expose:
      - '8080'
    networks:
      - backend
      - payment-processor
    environment:
      - LISTEN_ADDR=:8080
      - REDIS_URL=redis:6379
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
    depends_on:
      - redis
    deploy:
      resources:
        limits:
          cpus: '0.65'
          memory: '80MB'

  worker:
    build: .
    container_name: worker
    hostname: worker
    networks:
      - backend
      - payment-processor
    command: ["worker"]
    environment:
      - GIN_MODE=release
      - REDIS_URL=redis:6379
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
    depends_on:
      - redis
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '50MB'

  redis:
    image: redis:8-alpine
    container_name: redis
    hostname: redis
    ports:
      - 6666:6379
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: '30MB'

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true